server:
    port: 9000
    
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/db_inventory
        username: root
        password: 
    jpa:
        showSql: true
       
        main:
            bannerMode:off
        mail:
            protocol:smtp
            host:smtp.mailtrap.io
            port:2525
            username:{yourusername}
            password:{yourpassword}
               
##Email config
#spring.main.banner-mode=off
#spring.mail.protocol=smtp
#spring.mail.host=smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username={yourusername}
#spring.mail.password={yourpassword}
